### PR TITLE
Simple Rbac Adapter

### PR DESCRIPTION
**Pull request by m4rcsch**
I know the rule based thing is quite good. but must handle more than one role per user, so i had to create an own adapter.
There is no File Acces like in Nates Access Proposal, but will support that later.

What do you think?

### CODE REVIEW

**Comment by m4rcsch** [comment]
just realized that the README indents are somewhat confusing.. (if shown in the github file browser)

**Comment by tmaiaroto** [comment]
does this work? you have to run Auth::check() for each type of user? When do you run check() for each Auth configuration? Is it a different login action/page for each type of user?

**Comment by m4rcsch** [comment]
Hi Tom.

I`ve rewrote the Lib this morning and forgot to check against the $request in Auth. Nys and me fixed that, so it is working now!
So include the https://github.com/weluse/li3_access/commit/735a3f6556ff44837b21f2c0cd50c2498a821682

**Comment by m4rcsch** [comment]
Additional Info:
I defined Roles via Auth scope rules: user, editor, customer => i have to check the request/credentials against each role to know the ursers roles => one user has n roles.

**Comment by rich97** [comment]
Hi guys, I've made some changes to dgAlien's adapter. Please let me know what you think:

https://github.com/tmaiaroto/li3_access/pull/3

**Pull request merged**
