### PR TITLE
More changes!

### PR DESCRIPTION
**Pull request by rich97**
Hi there again.

I've given the AuthRbac class an update. I've simplified the class a lot and added a couple of things that should have been there from the start. It's mostly refactoring, but I was being granted access where I should not have been and this has fixed that.

There is one thing you might not like about this refactoring. There is a bit of an API change on the `li3_access\security\Access::check()` method:
-  public static function check($name, $user, $request, array $options = array()) {
-  public static function check($name, $request, $requester = null, array $options = array()) {

See this commit for details: https://github.com/rich97/li3_access/commit/be78a79986b384f596d518ebbf527ad451f6c914

### CODE REVIEW

**Comment by nateabele** [comment]
In any case, better (more accurate) terms would be `$requester` and `$resource`.

**Comment by rich97** [comment]
@nateabele Agreed. I will change that when I update the docblocks.

@tmaiaroto It wasn't really necessary. It just made more sense in the context of the AuthRbac adapter, and I'm not diametrically opposed to changing it back to the way it was.

The reason for the change is that in the AuthRbac adapter $requester is an optional parameter, if I didn't switch the parameters round then it would be called like so:

```
// manually set data
Access::check('rbac', $user, $this->request);
// check using the session or data is contained in $this->request->data
Access::check('rbac', false, $this->request);
```

Where in an ideal world it would be:

```
// manually set data
Access::check('rbac', $this->request, $data);
// check using the session or data is contained in $this->request->data
Access::check('rbac', $this->request);
```

But like I said if you feel like the change is too harsh then I'm willing to to put it back the way it was.

**Comment by rich97** [comment]
Another solution might be to make $requester a required parameter. But then that leaves you with:

```
Access::check('rbac', $this->request->data, $this->request);
```

So it's not a pretty solution.

**Comment by tmaiaroto** [comment]
Yea, I'm not sure false or null for that argument is so bad or uncommon. We see it in various other places too, where null or an object can be passed, followed by other args: $this->form->create(null, array('url' => ...)) for example... It's the adapter's choice to allow you to pass false or null instead of $this->request->data ... If an argument change were to be made, I'd lean more toward putting everything in an argument array so order can be taken out of the equation. 

Though I completely understand flipping them around would make things prettier looking in this adapter's case. The reasoning behind the order originally was because I was following along with Auth::check() 

That said, I'm not against a change, but I want to be careful not to open up a big hole in any code out there.

**Comment by rich97** [comment]
I'll change it back the way it was then. I understand it's a problem.

I don't have the time to do it right now, it'll have to be over the weekend so you can close this pull request if you like. Or just leave it open and I'll have it done next week.

Also, do you have any idea how to merge those readme updates into one commit? I kept uploading to Github to see how the readme file looks and every time I did it forced me to do a pull again before I could change it and push.

**Comment by tmaiaroto** [comment]
sounds strange, i've never really spent a lot of time playing around with those markdown files so i'm just not sure. sorry.

**Comment by rich97** [comment]
OK, so I've finally gotten round to making those changes, sorry it took so long, I've been busy.

You'll also notice a few QA fixes by Ciaro so thanks to him for that!

**Comment by Ciaro** [comment]
This request can be closed (merged in 9de3a7b67b).

**Pull request closed without merging**
